default: &DEFAULT
  num_epochs: 10
  batch_size: 256

MLP:
  <<: *DEFAULT
  model_name: mlp
  data_dir: "wikiArt" 
  checkpoint_dir: "checkpoints/mlp"
  log_dir: 'logs/mlp'
  dataset_class: "WikiArtDataset"
  flatten: True
  gpu_vis_dev: '0'
  num_epochs: 15
  batch_size: 128
  weight_decay: 0.0001
  step_size: 3
  lr: 0.01

CNN:
  <<: *DEFAULT
  model_name: cnn
  data_dir: "wikiArt"
  checkpoint_dir: "checkpoints/cnn"
  log_dir: 'logs/cnn'
  dataset_class: "WikiArtDataset"
  flatten: False
  gpu_vis_dev: '0'
  num_epochs: 10
  batch_size: 256
  weight_decay: 0.0001
  step_size: 3
  lr: 0.001

RESNET:
  <<: *DEFAULT
  model_name: resnet
  data_dir: "wikiArt"
  checkpoint_dir: "checkpoints/resnet"
  log_dir: 'logs/resnet'
  dataset_class: "WikiArtDataset"
  flatten: False
  gpu_vis_dev: '0'
  num_epochs: 10
  batch_size: 256
  weight_decay: 0.0001
  step_size: 3
  lr: 0.001


SVM:
  <<: *DEFAULT
  model_name: svm
  data_dir: "wikiArt"
  checkpoint_dir: "checkpoints/svm"
  log_dir: 'logs/svm'
  dataset_class: "WikiArtDataset"
  flatten: False
  gpu_vis_dev: '0'
  batch_size: 256
  lr: 0.001